-- MySQL Script generated by MySQL Workbench
-- 09/15/15 00:37:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eduaydre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eduaydre` ;

-- -----------------------------------------------------
-- Schema eduaydre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eduaydre` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `eduaydre` ;

-- -----------------------------------------------------
-- Table `eduaydre`.`ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ESTUDIANTE` (
  `carnet` INT NOT NULL,
  `nombre` TEXT NOT NULL,
  `apellido` TEXT NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `DPI` TEXT NULL,
  `telefono` TEXT NULL,
  PRIMARY KEY (`carnet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ENCARGADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ENCARGADO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ENCARGADO` (
  `id_encargado` INT NOT NULL,
  `nombre` TEXT NOT NULL,
  `apellido` TEXT NOT NULL,
  `fecha_nacimiento` TEXT NULL,
  `DPI` TEXT NULL,
  `telefono` TEXT NULL,
  `celular` TEXT NULL,
  PRIMARY KEY (`id_encargado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`CICLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`CICLO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`CICLO` (
  `ciclo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`ciclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`MAESTRO` (
  `id_maestro` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `apellido` TEXT NULL,
  `fecha_naciemiento` DATE NULL,
  `sexo` TINYINT(1) NULL,
  `DPI` TEXT NULL,
  `telefono` TEXT NULL,
  `celular` TEXT NULL,
  PRIMARY KEY (`id_maestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`GRADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`GRADO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`GRADO` (
  `grado` INT NOT NULL,
  `observacion` TEXT NULL,
  PRIMARY KEY (`grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`CURSO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`CURSO` (
  `grado` INT NOT NULL,
  `curso` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  INDEX `fk_CURSO_GRADO1_idx` (`grado` ASC),
  PRIMARY KEY (`curso`),
  CONSTRAINT `fk_CURSO_GRADO1`
    FOREIGN KEY (`grado`)
    REFERENCES `eduaydre`.`GRADO` (`grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ENCARGADO_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ENCARGADO_TIPO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ENCARGADO_TIPO` (
  `encargado_tipo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`encargado_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ENCARGADO_ESTUDIANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ENCARGADO_ESTUDIANTE` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ENCARGADO_ESTUDIANTE` (
  `id_encargado` INT NOT NULL,
  `carnet` INT NOT NULL,
  `encargado_tipo` INT NOT NULL,
  PRIMARY KEY (`id_encargado`, `carnet`, `encargado_tipo`),
  INDEX `fk_ENCARGADO_ESTUDIANTE_ESTUDIANTE1_idx` (`carnet` ASC),
  INDEX `fk_ENCARGADO_ESTUDIANTE_ENCARGADO_TIPO1_idx` (`encargado_tipo` ASC),
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ENCARGADO1`
    FOREIGN KEY (`id_encargado`)
    REFERENCES `eduaydre`.`ENCARGADO` (`id_encargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ENCARGADO_TIPO1`
    FOREIGN KEY (`encargado_tipo`)
    REFERENCES `eduaydre`.`ENCARGADO_TIPO` (`encargado_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SECCION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SECCION` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SECCION` (
  `seccion` INT NOT NULL,
  `grado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seccion`),
  INDEX `fk_SECCION_GRADO_idx` (`grado` ASC),
  CONSTRAINT `fk_SECCION_GRADO`
    FOREIGN KEY (`grado`)
    REFERENCES `eduaydre`.`GRADO` (`grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SECCION_CICLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SECCION_CICLO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SECCION_CICLO` (
  `seccion` INT NOT NULL,
  `ciclo` INT NOT NULL,
  PRIMARY KEY (`seccion`, `ciclo`),
  INDEX `fk_SECCION_CICLO_CICLO1_idx` (`ciclo` ASC),
  CONSTRAINT `fk_SECCION_CICLO_SECCION1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`SECCION` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_CICLO_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`CICLO` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ESTUDIANTE_SECCION_CICLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ESTUDIANTE_SECCION_CICLO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ESTUDIANTE_SECCION_CICLO` (
  `carnet` INT NOT NULL,
  `seccion` INT NOT NULL,
  `ciclo` INT NOT NULL,
  PRIMARY KEY (`carnet`, `seccion`, `ciclo`),
  INDEX `fk_ESTUDIANTE_SECCION_ESTUDIANTE1_idx` (`carnet` ASC),
  INDEX `fk_ESTUDIANTE_SECCION_SECCION_CICLO1_idx` (`seccion` ASC, `ciclo` ASC),
  CONSTRAINT `fk_ESTUDIANTE_SECCION_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_SECCION_SECCION_CICLO1`
    FOREIGN KEY (`seccion` , `ciclo`)
    REFERENCES `eduaydre`.`SECCION_CICLO` (`seccion` , `ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ESTUDIANTE_CICLO_CURSO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ESTUDIANTE_CICLO_CURSO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ESTUDIANTE_CICLO_CURSO` (
  `ciclo` INT NOT NULL,
  `curso` INT NOT NULL,
  `carnet` INT NOT NULL,
  PRIMARY KEY (`ciclo`, `curso`, `carnet`),
  INDEX `fk_table1_CURSO1_idx` (`curso` ASC),
  INDEX `fk_table1_ESTUDIANTE1_idx` (`carnet` ASC),
  CONSTRAINT `fk_table1_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`CICLO` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `eduaydre`.`CURSO` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`CICLO_CURSO_MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`CICLO_CURSO_MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`CICLO_CURSO_MAESTRO` (
  `ciclo` INT NOT NULL,
  `id_maestro` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`ciclo`, `id_maestro`, `curso`),
  INDEX `fk_table2_MAESTRO1_idx` (`id_maestro` ASC),
  INDEX `fk_CICLO_CURSO_MAESTRO_CURSO1_idx` (`curso` ASC),
  CONSTRAINT `fk_table2_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`CICLO` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_MAESTRO1`
    FOREIGN KEY (`id_maestro`)
    REFERENCES `eduaydre`.`MAESTRO` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CICLO_CURSO_MAESTRO_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `eduaydre`.`CURSO` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`UNIDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`UNIDAD` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`UNIDAD` (
  `unidad` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicial` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  PRIMARY KEY (`unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`TAREA_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`TAREA_TIPO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`TAREA_TIPO` (
  `tarea_tipo` INT NOT NULL,
  `nombre` TEXT NULL,
  PRIMARY KEY (`tarea_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`TAREA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`TAREA` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`TAREA` (
  `tarea` INT NOT NULL,
  `unidad` INT NOT NULL,
  `tipo_tarea` INT NOT NULL,
  `esExamen` TINYINT(1) NULL,
  `descripcion` INT NULL,
  `ruta_archivo` TEXT NULL,
  PRIMARY KEY (`tarea`),
  INDEX `fk_TAREA_UNIDAD1_idx` (`unidad` ASC),
  INDEX `fk_TAREA_TIPO_TAREA1_idx` (`tipo_tarea` ASC),
  CONSTRAINT `fk_TAREA_UNIDAD1`
    FOREIGN KEY (`unidad`)
    REFERENCES `eduaydre`.`UNIDAD` (`unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAREA_TIPO_TAREA1`
    FOREIGN KEY (`tipo_tarea`)
    REFERENCES `eduaydre`.`TAREA_TIPO` (`tarea_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SECCION_CICLO_CURSO_MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SECCION_CICLO_CURSO_MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SECCION_CICLO_CURSO_MAESTRO` (
  `seccion` INT NOT NULL,
  `ciclo` INT NOT NULL,
  `id_maestro` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`seccion`, `ciclo`, `id_maestro`, `curso`),
  INDEX `fk_SECCION_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `id_maestro` ASC, `curso` ASC),
  CONSTRAINT `fk_table1_SECCION1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`SECCION` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `id_maestro` , `curso`)
    REFERENCES `eduaydre`.`CICLO_CURSO_MAESTRO` (`ciclo` , `id_maestro` , `curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`TAREA_SECCION_CICLO_CURSO_MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`TAREA_SECCION_CICLO_CURSO_MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`TAREA_SECCION_CICLO_CURSO_MAESTRO` (
  `ciclo` INT NOT NULL,
  `curso` INT NOT NULL,
  `tarea` INT NOT NULL,
  `ponderacion` FLOAT NOT NULL,
  `fecha_limite` FLOAT NOT NULL,
  `tolerancia` TINYINT(1) NULL,
  `tiempo_tolerancia` DATETIME NULL,
  `porcentaje_tolerancia` FLOAT NULL,
  `aprobada` TINYINT(1) NULL,
  `seccion` INT NOT NULL,
  PRIMARY KEY (`ciclo`, `curso`, `tarea`, `seccion`),
  INDEX `fk_table3_TAREA1_idx` (`tarea` ASC),
  INDEX `fk_TAREA_SECCION_CICLO_CURSO_MAESTRO_SECCION_CICLO_CURSO_MA_idx` (`seccion` ASC),
  CONSTRAINT `fk_table3_TAREA1`
    FOREIGN KEY (`tarea`)
    REFERENCES `eduaydre`.`TAREA` (`tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAREA_SECCION_CICLO_CURSO_MAESTRO_SECCION_CICLO_CURSO_MAES1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`SECCION_CICLO_CURSO_MAESTRO` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`TAREA_CICLO_CURSO_MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`TAREA_CICLO_CURSO_MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`TAREA_CICLO_CURSO_MAESTRO` (
  `tarea` INT NOT NULL,
  `ciclo` INT NOT NULL,
  `maestro` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`tarea`, `ciclo`, `maestro`, `curso`),
  INDEX `fk_TAREA_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `maestro` ASC, `curso` ASC),
  CONSTRAINT `fk_table2_TAREA1`
    FOREIGN KEY (`tarea`)
    REFERENCES `eduaydre`.`TAREA` (`tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAREA_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `maestro` , `curso`)
    REFERENCES `eduaydre`.`CICLO_CURSO_MAESTRO` (`ciclo` , `id_maestro` , `curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SUPERVISOR_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SUPERVISOR_TIPO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SUPERVISOR_TIPO` (
  `supervisor_tipo` INT NOT NULL,
  `nombre` TEXT NOT NULL,
  PRIMARY KEY (`supervisor_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SUPERVISOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SUPERVISOR` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SUPERVISOR` (
  `id_supervisor` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL,
  `apellido` TEXT NULL,
  `fecha_nacimiento` DATE NULL,
  `DPI` TEXT NULL,
  `telefono` TEXT NULL,
  `celular` TEXT NULL,
  `supervisor_tipo` INT NOT NULL,
  PRIMARY KEY (`id_supervisor`),
  INDEX `fk_SUPERVISOR_SUPERVISOR_TIPO1_idx` (`supervisor_tipo` ASC),
  CONSTRAINT `fk_SUPERVISOR_SUPERVISOR_TIPO1`
    FOREIGN KEY (`supervisor_tipo`)
    REFERENCES `eduaydre`.`SUPERVISOR_TIPO` (`supervisor_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SECCION_CICLO_SUPERVISOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SECCION_CICLO_SUPERVISOR` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SECCION_CICLO_SUPERVISOR` (
  `id_supervisor` INT NOT NULL,
  `seccion` INT NOT NULL,
  `ciclo` INT NOT NULL,
  PRIMARY KEY (`id_supervisor`, `seccion`, `ciclo`),
  INDEX `fk_table4_SUPERVISOR1_idx` (`id_supervisor` ASC),
  INDEX `fk_SECCION_CICLO_CURSO_MAESTRO_SUPERVISOR_SECCION_CICLO1_idx` (`seccion` ASC, `ciclo` ASC),
  CONSTRAINT `fk_table4_SUPERVISOR1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `eduaydre`.`SUPERVISOR` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_CICLO_CURSO_MAESTRO_SUPERVISOR_SECCION_CICLO1`
    FOREIGN KEY (`seccion` , `ciclo`)
    REFERENCES `eduaydre`.`SECCION_CICLO` (`seccion` , `ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`SUPERVISOR_MAESTRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`SUPERVISOR_MAESTRO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`SUPERVISOR_MAESTRO` (
  `id_maestro` INT NOT NULL,
  `id_supervisor` INT NOT NULL,
  PRIMARY KEY (`id_maestro`, `id_supervisor`),
  INDEX `fk_SUPERVISOR_MAESTRO_SUPERVISOR1_idx` (`id_supervisor` ASC),
  CONSTRAINT `fk_SUPERVISOR_MAESTRO_MAESTRO1`
    FOREIGN KEY (`id_maestro`)
    REFERENCES `eduaydre`.`MAESTRO` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPERVISOR_MAESTRO_SUPERVISOR1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `eduaydre`.`SUPERVISOR` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`NOTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`NOTA` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`NOTA` (
  `carnet` INT NOT NULL,
  `nota_obtenida` FLOAT NOT NULL,
  `fecha_de_envio` DATE NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `ciclo` INT NOT NULL,
  `curso` INT NOT NULL,
  `tarea` INT NOT NULL,
  `seccion` INT NOT NULL,
  `ruta_archivo` TEXT NULL,
  PRIMARY KEY (`carnet`, `ciclo`, `curso`, `tarea`, `seccion`),
  INDEX `fk_table1_ESTUDIANTE2_idx` (`carnet` ASC),
  INDEX `fk_NOTA_TAREA_SECCION_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `curso` ASC, `tarea` ASC, `seccion` ASC),
  CONSTRAINT `fk_table1_ESTUDIANTE2`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_TAREA_SECCION_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `curso` , `tarea` , `seccion`)
    REFERENCES `eduaydre`.`TAREA_SECCION_CICLO_CURSO_MAESTRO` (`ciclo` , `curso` , `tarea` , `seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`TIPO_MOTIVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`TIPO_MOTIVO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`TIPO_MOTIVO` (
  `tipo_motivo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`tipo_motivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`MOTIVO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`MOTIVO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`MOTIVO` (
  `motivo` INT NOT NULL,
  `tipo_motivo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`motivo`),
  INDEX `fk_MOTIVO_TIPO_MOTIVO1_idx` (`tipo_motivo` ASC),
  CONSTRAINT `fk_MOTIVO_TIPO_MOTIVO1`
    FOREIGN KEY (`tipo_motivo`)
    REFERENCES `eduaydre`.`TIPO_MOTIVO` (`tipo_motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`MOTIVO_ESTUDIANTE_CICLO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`MOTIVO_ESTUDIANTE_CICLO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`MOTIVO_ESTUDIANTE_CICLO` (
  `motivo` INT NOT NULL,
  `carnet` INT NOT NULL,
  `ciclo` INT NOT NULL,
  `fecha_de_puesto` BLOB NULL,
  `ponderacion` INT NULL,
  `observacion` TEXT NULL,
  PRIMARY KEY (`motivo`, `carnet`, `ciclo`),
  INDEX `fk_MOTIVO_ESTUDIANTE_CICLO_ESTUDIANTE1_idx` (`carnet` ASC),
  INDEX `fk_MOTIVO_ESTUDIANTE_CICLO_CICLO1_idx` (`ciclo` ASC),
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_MOTIVO1`
    FOREIGN KEY (`motivo`)
    REFERENCES `eduaydre`.`MOTIVO` (`motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`CICLO` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`REPORTE_TIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`REPORTE_TIPO` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`REPORTE_TIPO` (
  `reporte_tipo` INT NOT NULL,
  `nombre` TEXT NULL,
  PRIMARY KEY (`reporte_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`REPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`REPORTE` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`REPORTE` (
  `reporte` INT NOT NULL,
  `reporte_tipo` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `asunto` TEXT NULL,
  PRIMARY KEY (`reporte`),
  INDEX `fk_REPORTE_REPORTE_TIPO1_idx` (`reporte_tipo` ASC),
  CONSTRAINT `fk_REPORTE_REPORTE_TIPO1`
    FOREIGN KEY (`reporte_tipo`)
    REFERENCES `eduaydre`.`REPORTE_TIPO` (`reporte_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`ESTUDIANTE_REPORTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ESTUDIANTE_REPORTE` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ESTUDIANTE_REPORTE` (
  `carnet` INT NOT NULL,
  `reporte` INT NOT NULL,
  `fecha_envio` DATE NULL,
  `enviado` TINYINT(1) NULL,
  `fecha_aprobado` INT NULL,
  `aprobado` TINYINT(1) NULL,
  PRIMARY KEY (`carnet`, `reporte`),
  INDEX `fk_table1_REPORTE1_idx` (`reporte` ASC),
  CONSTRAINT `fk_table1_ESTUDIANTE3`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`ESTUDIANTE` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_REPORTE1`
    FOREIGN KEY (`reporte`)
    REFERENCES `eduaydre`.`REPORTE` (`reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
