-- MySQL Script generated by MySQL Workbench
-- 10/13/15 23:37:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eduaydre
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eduaydre` ;

-- -----------------------------------------------------
-- Schema eduaydre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eduaydre` DEFAULT CHARACTER SET utf8 ;
USE `eduaydre` ;

-- -----------------------------------------------------
-- Table `eduaydre`.`ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ciclo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ciclo` (
  `ciclo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT '',
  `fecha_inicio` DATE NULL DEFAULT NULL COMMENT '',
  `fecha_fin` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ciclo`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`grado` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`grado` (
  `grado` INT(11) NOT NULL COMMENT '',
  `observacion` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`grado`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`curso` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`curso` (
  `grado` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`curso`)  COMMENT '',
  INDEX `fk_CURSO_GRADO1_idx` (`grado` ASC)  COMMENT '',
  CONSTRAINT `fk_CURSO_GRADO1`
    FOREIGN KEY (`grado`)
    REFERENCES `eduaydre`.`grado` (`grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`maestro` (
  `id_maestro` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  `apellido` TEXT NULL DEFAULT NULL COMMENT '',
  `fecha_naciemiento` DATE NULL DEFAULT NULL COMMENT '',
  `sexo` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `DPI` TEXT NULL DEFAULT NULL COMMENT '',
  `telefono` TEXT NULL DEFAULT NULL COMMENT '',
  `celular` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_maestro`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`ciclo_curso_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`ciclo_curso_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`ciclo_curso_maestro` (
  `ciclo` INT(11) NOT NULL COMMENT '',
  `id_maestro` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ciclo`, `id_maestro`, `curso`)  COMMENT '',
  INDEX `fk_table2_MAESTRO1_idx` (`id_maestro` ASC)  COMMENT '',
  INDEX `fk_CICLO_CURSO_MAESTRO_CURSO1_idx` (`curso` ASC)  COMMENT '',
  CONSTRAINT `fk_CICLO_CURSO_MAESTRO_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `eduaydre`.`curso` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`ciclo` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_MAESTRO1`
    FOREIGN KEY (`id_maestro`)
    REFERENCES `eduaydre`.`maestro` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`encargado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`encargado` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`encargado` (
  `id_encargado` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NOT NULL COMMENT '',
  `apellido` TEXT NOT NULL COMMENT '',
  `fecha_nacimiento` TEXT NULL DEFAULT NULL COMMENT '',
  `DPI` TEXT NULL DEFAULT NULL COMMENT '',
  `telefono` TEXT NULL DEFAULT NULL COMMENT '',
  `celular` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_encargado`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`encargado_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`encargado_tipo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`encargado_tipo` (
  `encargado_tipo` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`encargado_tipo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`estudiante` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`estudiante` (
  `carnet` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NOT NULL COMMENT '',
  `apellido` TEXT NOT NULL COMMENT '',
  `fecha_nacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `DPI` TEXT NULL DEFAULT NULL COMMENT '',
  `telefono` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`carnet`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`encargado_estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`encargado_estudiante` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`encargado_estudiante` (
  `id_encargado` INT(11) NOT NULL COMMENT '',
  `carnet` INT(11) NOT NULL COMMENT '',
  `encargado_tipo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_encargado`, `carnet`, `encargado_tipo`)  COMMENT '',
  INDEX `fk_ENCARGADO_ESTUDIANTE_ESTUDIANTE1_idx` (`carnet` ASC)  COMMENT '',
  INDEX `fk_ENCARGADO_ESTUDIANTE_ENCARGADO_TIPO1_idx` (`encargado_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ENCARGADO1`
    FOREIGN KEY (`id_encargado`)
    REFERENCES `eduaydre`.`encargado` (`id_encargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ENCARGADO_TIPO1`
    FOREIGN KEY (`encargado_tipo`)
    REFERENCES `eduaydre`.`encargado_tipo` (`encargado_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENCARGADO_ESTUDIANTE_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`estudiante_ciclo_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`estudiante_ciclo_curso` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`estudiante_ciclo_curso` (
  `ciclo` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  `carnet` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ciclo`, `curso`, `carnet`)  COMMENT '',
  INDEX `fk_table1_CURSO1_idx` (`curso` ASC)  COMMENT '',
  INDEX `fk_table1_ESTUDIANTE1_idx` (`carnet` ASC)  COMMENT '',
  CONSTRAINT `fk_table1_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`ciclo` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_CURSO1`
    FOREIGN KEY (`curso`)
    REFERENCES `eduaydre`.`curso` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`reporte_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`reporte_tipo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`reporte_tipo` (
  `reporte_tipo` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`reporte_tipo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`reporte` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`reporte` (
  `reporte` INT(11) NOT NULL COMMENT '',
  `reporte_tipo` INT(11) NOT NULL COMMENT '',
  `descripcion` TEXT NOT NULL COMMENT '',
  `asunto` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`reporte`)  COMMENT '',
  INDEX `fk_REPORTE_REPORTE_TIPO1_idx` (`reporte_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_REPORTE_REPORTE_TIPO1`
    FOREIGN KEY (`reporte_tipo`)
    REFERENCES `eduaydre`.`reporte_tipo` (`reporte_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`estudiante_reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`estudiante_reporte` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`estudiante_reporte` (
  `carnet` INT(11) NOT NULL COMMENT '',
  `reporte` INT(11) NOT NULL COMMENT '',
  `fecha_envio` DATE NULL DEFAULT NULL COMMENT '',
  `enviado` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `fecha_aprobado` INT(11) NULL DEFAULT NULL COMMENT '',
  `aprobado` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`carnet`, `reporte`)  COMMENT '',
  INDEX `fk_table1_REPORTE1_idx` (`reporte` ASC)  COMMENT '',
  CONSTRAINT `fk_table1_ESTUDIANTE3`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_REPORTE1`
    FOREIGN KEY (`reporte`)
    REFERENCES `eduaydre`.`reporte` (`reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`seccion` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`seccion` (
  `seccion` INT(11) NOT NULL COMMENT '',
  `grado` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`seccion`)  COMMENT '',
  INDEX `fk_SECCION_GRADO_idx` (`grado` ASC)  COMMENT '',
  CONSTRAINT `fk_SECCION_GRADO`
    FOREIGN KEY (`grado`)
    REFERENCES `eduaydre`.`grado` (`grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`seccion_ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`seccion_ciclo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`seccion_ciclo` (
  `seccion` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`seccion`, `ciclo`)  COMMENT '',
  INDEX `fk_SECCION_CICLO_CICLO1_idx` (`ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_SECCION_CICLO_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`ciclo` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECCION_CICLO_SECCION1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`seccion` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`estudiante_seccion_ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`estudiante_seccion_ciclo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`estudiante_seccion_ciclo` (
  `carnet` INT(11) NOT NULL COMMENT '',
  `seccion` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`carnet`, `seccion`, `ciclo`)  COMMENT '',
  INDEX `fk_ESTUDIANTE_SECCION_ESTUDIANTE1_idx` (`carnet` ASC)  COMMENT '',
  INDEX `fk_ESTUDIANTE_SECCION_SECCION_CICLO1_idx` (`seccion` ASC, `ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTUDIANTE_SECCION_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESTUDIANTE_SECCION_SECCION_CICLO1`
    FOREIGN KEY (`seccion` , `ciclo`)
    REFERENCES `eduaydre`.`seccion_ciclo` (`seccion` , `ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`tipo_motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`tipo_motivo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`tipo_motivo` (
  `tipo_motivo` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`tipo_motivo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`motivo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`motivo` (
  `motivo` INT(11) NOT NULL COMMENT '',
  `tipo_motivo` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`motivo`)  COMMENT '',
  INDEX `fk_MOTIVO_TIPO_MOTIVO1_idx` (`tipo_motivo` ASC)  COMMENT '',
  CONSTRAINT `fk_MOTIVO_TIPO_MOTIVO1`
    FOREIGN KEY (`tipo_motivo`)
    REFERENCES `eduaydre`.`tipo_motivo` (`tipo_motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`motivo_estudiante_ciclo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`motivo_estudiante_ciclo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`motivo_estudiante_ciclo` (
  `motivo` INT(11) NOT NULL COMMENT '',
  `carnet` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  `fecha_de_puesto` BLOB NULL DEFAULT NULL COMMENT '',
  `ponderacion` INT(11) NULL DEFAULT NULL COMMENT '',
  `observacion` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`motivo`, `carnet`, `ciclo`)  COMMENT '',
  INDEX `fk_MOTIVO_ESTUDIANTE_CICLO_ESTUDIANTE1_idx` (`carnet` ASC)  COMMENT '',
  INDEX `fk_MOTIVO_ESTUDIANTE_CICLO_CICLO1_idx` (`ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_CICLO1`
    FOREIGN KEY (`ciclo`)
    REFERENCES `eduaydre`.`ciclo` (`ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_ESTUDIANTE1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOTIVO_ESTUDIANTE_CICLO_MOTIVO1`
    FOREIGN KEY (`motivo`)
    REFERENCES `eduaydre`.`motivo` (`motivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`seccion_ciclo_curso_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`seccion_ciclo_curso_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`seccion_ciclo_curso_maestro` (
  `seccion` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  `id_maestro` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`seccion`, `ciclo`, `id_maestro`, `curso`)  COMMENT '',
  INDEX `fk_SECCION_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `id_maestro` ASC, `curso` ASC)  COMMENT '',
  CONSTRAINT `fk_SECCION_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `id_maestro` , `curso`)
    REFERENCES `eduaydre`.`ciclo_curso_maestro` (`ciclo` , `id_maestro` , `curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_SECCION1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`seccion` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`tarea_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`tarea_tipo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`tarea_tipo` (
  `tarea_tipo` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`tarea_tipo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`unidad` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`unidad` (
  `unidad` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fecha_inicial` DATETIME NOT NULL COMMENT '',
  `fecha_final` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`unidad`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`tarea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`tarea` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`tarea` (
  `tarea` INT(11) NOT NULL COMMENT '',
  `unidad` INT(11) NOT NULL COMMENT '',
  `tipo_tarea` INT(11) NOT NULL COMMENT '',
  `esExamen` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `ruta_archivo` TEXT NULL DEFAULT NULL COMMENT '',
  `descripcion` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`tarea`)  COMMENT '',
  INDEX `fk_TAREA_UNIDAD1_idx` (`unidad` ASC)  COMMENT '',
  INDEX `fk_TAREA_TIPO_TAREA1_idx` (`tipo_tarea` ASC)  COMMENT '',
  CONSTRAINT `fk_TAREA_TIPO_TAREA1`
    FOREIGN KEY (`tipo_tarea`)
    REFERENCES `eduaydre`.`tarea_tipo` (`tarea_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAREA_UNIDAD1`
    FOREIGN KEY (`unidad`)
    REFERENCES `eduaydre`.`unidad` (`unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`tarea_seccion_ciclo_curso_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`tarea_seccion_ciclo_curso_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`tarea_seccion_ciclo_curso_maestro` (
  `ciclo` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  `tarea` INT(11) NOT NULL COMMENT '',
  `ponderacion` FLOAT NOT NULL COMMENT '',
  `tolerancia` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `tiempo_tolerancia` DATETIME NULL DEFAULT NULL COMMENT '',
  `porcentaje_tolerancia` FLOAT NULL DEFAULT NULL COMMENT '',
  `aprobada` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `seccion` INT(11) NOT NULL COMMENT '',
  `fecha_limite` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`ciclo`, `curso`, `tarea`, `seccion`)  COMMENT '',
  INDEX `fk_table3_TAREA1_idx` (`tarea` ASC)  COMMENT '',
  INDEX `fk_TAREA_SECCION_CICLO_CURSO_MAESTRO_SECCION_CICLO_CURSO_MA_idx` (`seccion` ASC)  COMMENT '',
  CONSTRAINT `fk_TAREA_SECCION_CICLO_CURSO_MAESTRO_SECCION_CICLO_CURSO_MAES1`
    FOREIGN KEY (`seccion`)
    REFERENCES `eduaydre`.`seccion_ciclo_curso_maestro` (`seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table3_TAREA1`
    FOREIGN KEY (`tarea`)
    REFERENCES `eduaydre`.`tarea` (`tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`nota` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`nota` (
  `carnet` INT(11) NOT NULL COMMENT '',
  `nota_obtenida` FLOAT NOT NULL COMMENT '',
  `fecha_de_envio` DATETIME NOT NULL COMMENT '',
  `observacion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  `tarea` INT(11) NOT NULL COMMENT '',
  `seccion` INT(11) NOT NULL COMMENT '',
  `ruta_archivo` TEXT NULL DEFAULT NULL COMMENT '',
  `fecha_calificacion` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`carnet`, `ciclo`, `curso`, `tarea`, `seccion`)  COMMENT '',
  INDEX `fk_table1_ESTUDIANTE2_idx` (`carnet` ASC)  COMMENT '',
  INDEX `fk_NOTA_TAREA_SECCION_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `curso` ASC, `tarea` ASC, `seccion` ASC)  COMMENT '',
  CONSTRAINT `fk_NOTA_TAREA_SECCION_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `curso` , `tarea` , `seccion`)
    REFERENCES `eduaydre`.`tarea_seccion_ciclo_curso_maestro` (`ciclo` , `curso` , `tarea` , `seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_ESTUDIANTE2`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`supervisor_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`supervisor_tipo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`supervisor_tipo` (
  `supervisor_tipo` INT(11) NOT NULL COMMENT '',
  `nombre` TEXT NOT NULL COMMENT '',
  PRIMARY KEY (`supervisor_tipo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`supervisor` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`supervisor` (
  `id_supervisor` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` TEXT NULL DEFAULT NULL COMMENT '',
  `apellido` TEXT NULL DEFAULT NULL COMMENT '',
  `fecha_nacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `DPI` TEXT NULL DEFAULT NULL COMMENT '',
  `telefono` TEXT NULL DEFAULT NULL COMMENT '',
  `celular` TEXT NULL DEFAULT NULL COMMENT '',
  `supervisor_tipo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_supervisor`)  COMMENT '',
  INDEX `fk_SUPERVISOR_SUPERVISOR_TIPO1_idx` (`supervisor_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_SUPERVISOR_SUPERVISOR_TIPO1`
    FOREIGN KEY (`supervisor_tipo`)
    REFERENCES `eduaydre`.`supervisor_tipo` (`supervisor_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`seccion_ciclo_supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`seccion_ciclo_supervisor` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`seccion_ciclo_supervisor` (
  `id_supervisor` INT(11) NOT NULL COMMENT '',
  `seccion` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_supervisor`, `seccion`, `ciclo`)  COMMENT '',
  INDEX `fk_table4_SUPERVISOR1_idx` (`id_supervisor` ASC)  COMMENT '',
  INDEX `fk_SECCION_CICLO_CURSO_MAESTRO_SUPERVISOR_SECCION_CICLO1_idx` (`seccion` ASC, `ciclo` ASC)  COMMENT '',
  CONSTRAINT `fk_SECCION_CICLO_CURSO_MAESTRO_SUPERVISOR_SECCION_CICLO1`
    FOREIGN KEY (`seccion` , `ciclo`)
    REFERENCES `eduaydre`.`seccion_ciclo` (`seccion` , `ciclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table4_SUPERVISOR1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `eduaydre`.`supervisor` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`supervisor_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`supervisor_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`supervisor_maestro` (
  `id_maestro` INT(11) NOT NULL COMMENT '',
  `id_supervisor` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_maestro`, `id_supervisor`)  COMMENT '',
  INDEX `fk_SUPERVISOR_MAESTRO_SUPERVISOR1_idx` (`id_supervisor` ASC)  COMMENT '',
  CONSTRAINT `fk_SUPERVISOR_MAESTRO_MAESTRO1`
    FOREIGN KEY (`id_maestro`)
    REFERENCES `eduaydre`.`maestro` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPERVISOR_MAESTRO_SUPERVISOR1`
    FOREIGN KEY (`id_supervisor`)
    REFERENCES `eduaydre`.`supervisor` (`id_supervisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`tarea_ciclo_curso_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`tarea_ciclo_curso_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`tarea_ciclo_curso_maestro` (
  `tarea` INT(11) NOT NULL COMMENT '',
  `ciclo` INT(11) NOT NULL COMMENT '',
  `maestro` INT(11) NOT NULL COMMENT '',
  `curso` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`tarea`, `ciclo`, `maestro`, `curso`)  COMMENT '',
  INDEX `fk_TAREA_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1_idx` (`ciclo` ASC, `maestro` ASC, `curso` ASC)  COMMENT '',
  CONSTRAINT `fk_TAREA_CICLO_CURSO_MAESTRO_CICLO_CURSO_MAESTRO1`
    FOREIGN KEY (`ciclo` , `maestro` , `curso`)
    REFERENCES `eduaydre`.`ciclo_curso_maestro` (`ciclo` , `id_maestro` , `curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_TAREA1`
    FOREIGN KEY (`tarea`)
    REFERENCES `eduaydre`.`tarea` (`tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eduaydre`.`usuario_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`usuario_tipo` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`usuario_tipo` (
  `usuario_tipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`usuario_tipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`usuario` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`usuario` (
  `usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `pass` VARCHAR(45) NULL COMMENT '',
  `usuario_tipo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`usuario`)  COMMENT '',
  INDEX `fk_usuario_usuario_tipo1_idx` (`usuario_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_usuario_tipo1`
    FOREIGN KEY (`usuario_tipo`)
    REFERENCES `eduaydre`.`usuario_tipo` (`usuario_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`usuario_maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`usuario_maestro` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`usuario_maestro` (
  `id_maestro` INT(11) NOT NULL COMMENT '',
  `usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_maestro`, `usuario`)  COMMENT '',
  INDEX `fk_usuario_maestro_usuario1_idx` (`usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_maestro_maestro1`
    FOREIGN KEY (`id_maestro`)
    REFERENCES `eduaydre`.`maestro` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_maestro_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `eduaydre`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eduaydre`.`usuario_estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eduaydre`.`usuario_estudiante` ;

CREATE TABLE IF NOT EXISTS `eduaydre`.`usuario_estudiante` (
  `usuario` INT NOT NULL COMMENT '',
  `carnet` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`usuario`, `carnet`)  COMMENT '',
  INDEX `fk_usuario_estudiante_estudiante1_idx` (`carnet` ASC)  COMMENT '',
  CONSTRAINT `fk_usuario_estudiante_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `eduaydre`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_estudiante_estudiante1`
    FOREIGN KEY (`carnet`)
    REFERENCES `eduaydre`.`estudiante` (`carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `eduaydre` ;

-- -----------------------------------------------------
-- procedure get_examenes_maestro_curso
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`get_examenes_maestro_curso`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `get_examenes_maestro_curso`(in cicloP int, in cursoP int, in maestroP int)
begin
select t.* 
from tarea_ciclo_curso_maestro tccm
inner join tarea t on tccm.tarea = t.tarea
where tccm.ciclo = cicloP and tccm.curso = cursoP and  tccm.maestro = maestroP and t.esExamen = 1 ;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_cursos_ciclos_from_estudiante
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_cursos_ciclos_from_estudiante`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_cursos_ciclos_from_estudiante`(in p_carnet int,in p_ciclo int)
BEGIN

select ecc.ciclo,c.curso,c.nombre,esc.seccion
from estudiante_ciclo_curso ecc, curso c, estudiante_seccion_ciclo esc
where ecc.carnet=p_carnet and ecc.ciclo=p_ciclo and ecc.curso=c.curso
and esc.carnet=ecc.carnet and esc.ciclo=p_ciclo
;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_cursos_ciclos_from_maestro
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_cursos_ciclos_from_maestro`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_cursos_ciclos_from_maestro`(in id_maestro int,in ciclo int)
BEGIN
select sccm.seccion, s.nombre 'nombre_seccion', 
sccm.curso, c.nombre 'nombre_curso',  g.observacion 'descripcion_grado'
from seccion_ciclo_curso_maestro as sccm, seccion as s, curso as c,
grado as g
where sccm.id_maestro=id_maestro and sccm.ciclo=ciclo and sccm.seccion=s.seccion 
and sccm.curso=c.curso and s.grado=g.grado;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_estudiante_por_curso
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_estudiante_por_curso`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_estudiante_por_curso`(in curso int , in ciclo int)
begin
	select e.carnet, e.nombre, e.apellido from estudiante e
	inner join  estudiante_ciclo_curso ecc on e.carnet = ecc.carnet ;
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_estudiantes_curso_seccion_ciclo
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_estudiantes_curso_seccion_ciclo`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_estudiantes_curso_seccion_ciclo`(in p_ciclo int, in p_curso int,in p_seccion int)
begin

select esc.carnet, e.nombre,e.apellido  
from estudiante_seccion_ciclo esc, estudiante_ciclo_curso ecc, estudiante e
where esc.carnet=ecc.carnet and esc.ciclo=ecc.ciclo and esc.carnet=e.carnet
and esc.ciclo=p_ciclo and ecc.curso=p_curso and esc.seccion=p_seccion
order by e.apellido; 

end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_notas_from_estudiante_curso_ciclo
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_notas_from_estudiante_curso_ciclo`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_notas_from_estudiante_curso_ciclo`(
in p_carnet int,in p_curso int,in p_ciclo int,in p_unidad int)
BEGIN

select n.nota_obtenida,n.fecha_de_envio,t.descripcion,n.tarea,n.fecha_calificacion,tt.nombre as 'tipo_tarea',tsccm.ponderacion
-- select *
from nota n, tarea t, tarea_tipo tt,tarea_seccion_ciclo_curso_maestro tsccm
where n.carnet = p_carnet and n.ciclo=p_ciclo 
and n.curso=p_curso and n.tarea=t.tarea and t.unidad=p_unidad and t.tipo_tarea=tt.tarea_tipo
and t.tarea=tsccm.tarea and tsccm.ciclo=n.ciclo and tsccm.curso=n.curso
;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_get_tareas_curso_seccion_ciclo_unidad
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_get_tareas_curso_seccion_ciclo_unidad`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_get_tareas_curso_seccion_ciclo_unidad`(in p_ciclo int, in p_curso int,in p_seccion int,in p_unidad int)
begin

select  tsccm.ciclo, tsccm.curso,tsccm.tarea,tsccm.ponderacion,tsccm.tolerancia,tsccm.tiempo_tolerancia,tsccm.porcentaje_tolerancia,
tsccm.aprobada, tsccm.fecha_limite, t.unidad,t.tipo_tarea,t.esExamen, t.descripcion
from tarea_seccion_ciclo_curso_maestro tsccm, tarea t
where tsccm.ciclo=p_ciclo and tsccm.curso=p_curso and tsccm.seccion=p_seccion
and tsccm.tarea=t.tarea and t.unidad=p_unidad;

end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_guardar_nota_from_maestro
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_guardar_nota_from_maestro`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_guardar_nota_from_maestro`(in p_carnet int, in p_nota_obtenida int,
in p_ciclo int,in p_curso int,in p_tarea int,in p_seccion int)
begin

INSERT INTO `eduaydre`.`nota`
(`carnet`,
`nota_obtenida`,
`fecha_de_envio`,
`ciclo`,
`curso`,
`tarea`,
`seccion`,
`fecha_calificacion`)
VALUES
(p_carnet,
p_nota_obtenida,
NOW(),
p_ciclo,
p_curso,
p_tarea,
p_seccion,
NOW())
ON DUPLICATE KEY UPDATE    
nota_obtenida=VALUES(nota_obtenida), 
fecha_calificacion=VALUES(fecha_calificacion);

end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_insert_tarea_from_maestro
-- -----------------------------------------------------

USE `eduaydre`;
DROP procedure IF EXISTS `eduaydre`.`sp_insert_tarea_from_maestro`;

DELIMITER $$
USE `eduaydre`$$
CREATE DEFINER=`soft`@`localhost` PROCEDURE `sp_insert_tarea_from_maestro`(
in p_unidad int,in p_tipo_tarea int, in p_ciclo int, in p_maestro int, in p_curso int, in p_seccion int,
in p_es_examen int, in p_descripcion text, in p_ruta_archivo text,
in p_ponderacion int, in p_fecha_limite datetime, in p_toleraciona tinyint, in p_tiempo_tolerancia datetime, in p_porcentaje_tolerancia int, in p_aprobada tinyint)
BEGIN

DECLARE nueva_llave_tarea INT DEFAULT 0;
SELECT count(tarea)+1 from tarea into nueva_llave_tarea;

INSERT INTO tarea(`tarea`, `unidad`, `tipo_tarea`, `esExamen`, `ruta_archivo`, `descripcion`) 
VALUES (nueva_llave_tarea, p_unidad, p_tipo_tarea, p_es_examen, p_ruta_archivo, p_descripcion);


INSERT INTO `eduaydre`.`tarea_ciclo_curso_maestro` (`tarea`, `ciclo`, `maestro`, `curso`) 
VALUES (nueva_llave_tarea, p_ciclo, p_maestro, p_curso);

INSERT INTO tarea_seccion_ciclo_curso_maestro 
(`ciclo`, `curso`, `tarea`, `ponderacion`, `fecha_limite`, `tolerancia`, `tiempo_tolerancia`, `porcentaje_tolerancia`, `aprobada`, `seccion`) 
VALUES (p_ciclo, p_curso, nueva_llave_tarea, p_ponderacion, p_fecha_limite, p_toleraciona, p_tiempo_tolerancia, p_porcentaje_tolerancia, p_aprobada, p_seccion);


END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
